name: fkn
description: A Flutter project for FCS.
publish_to: 'none'

version: 2.0.2+70

environment:
  #  не понижать версию ниже 3.12, может полететь firebase на ios (но это не точно)
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.7.1
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.1.0
  shimmer_animation: ^2.1.0+1
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.2
  webview_flutter: ^4.7.0
  package_info: ^2.0.2
  provider: ^6.0.5
  get_it: ^7.2.0
  dio: ^5.4.0
  device_info:
  flutter_svg: ^2.0.9
  measure_size: ^4.0.0
  pretty_dio_logger:
  auto_route: ^7.8.4
  shared_preferences: ^2.0.15
  uni_links: ^0.5.1
  freezed_annotation: ^2.4.1
  home_widget: ^0.4.0
  workmanager: ^0.5.1
  json_annotation: ^4.8.1
  http: ^1.2.0
  expandable_page_view: ^1.0.17
  flutter_secure_storage: ^9.0.0
  mutex: any
  connectivity_plus: ^5.0.2
  retrofit: ^4.0.3
  carousel_slider: ^4.2.1
  lottie: ^3.0.0
  onesignal_flutter: ^5.1.0
  modal_bottom_sheet:
    git:
      url: https://github.com/netos23/modal_bottom_sheet.git
      ref: fix/migrate_flutter_3_7
      path: modal_bottom_sheet
  firebase_crashlytics: ^3.4.9
  url_launcher: ^6.2.3
  flutter_localization: any
  intl: ^0.19.0
  table_calendar: ^3.0.9
  appmetrica_plugin: ^1.4.0
  firebase_core: ^2.24.2
  store_redirect: ^2.0.1
  pub_semver: ^2.1.4
  uuid: ^4.5.1
  flutter_native_splash: ^2.3.9
  flutter_secure_storage_platform_interface: ^1.0.1
  flutter_portal: ^1.1.4
  easy_debounce: ^2.0.3
  animated_text_kit: ^4.2.2
  permission_handler: ^11.3.0
  app_tracking_transparency: ^2.0.4
  app_settings: ^5.1.1

  linked_scroll_controller: ^0.2.0
  loading_indicator: ^3.1.1
  syncfusion_flutter_pdfviewer: ^28.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=7.0.0 <8.0.0'
  injectable_generator:
  build_runner: ^2.4.7
  auto_route_generator:
  injectable: ^2.3.5
  freezed: ^2.4.6
  integration_test:
    sdk: flutter
  flutter_svg_test: ^1.0.0

  # Testing
  golden_toolkit: ^0.15.0
  mocktail_image_network: ^1.1.0
  mocktail: ^1.0.3
#  animated_native_splash:
#    git:
#      url: https://github.com/Crabishka/flutter_animated_splash_screen.git
#      ref: master


#animated_native_splash:
#  jsonFile: assets/splash.json


flutter_native_splash:
  image: assets/splash_icon.png
  color: "#ffffff"
  android_12:
    image: assets/splash_icon.png



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/image/
    - assets/image/mocks/
    - assets/image/schedule/
    - assets/image/blur/


  fonts:
    - family: BottomNavigationBarIcon
      fonts:
        - asset: assets/BottomNavigationBarIcon.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100