/// Flutter icons BottomNavigationBarIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BottomNavigationBarIcon
///      fonts:
///       - asset: fonts/BottomNavigationBarIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BottomNavigationBarIcon {
  BottomNavigationBarIcon._();

  static const _kFontFam = 'BottomNavigationBarIcon';
  static const String? _kFontPkg = null;

  static const IconData timetable = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData career = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData showcase = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
